---
# File:

- name: install bundle
  shell: "{{ source_profile_command }} && bundle install"
  args:
    chdir: "{{ deployment_timestamped_release_path }}"
    executable: /bin/bash

- name: start web application on port {{ application_port }}
  shell: "{{ source_profile_command }} && nohup bundle exec rackup -p {{ application_port }} &"
  args:
    chdir: "{{ deployment_timestamped_release_path }}"
    executable: /bin/bash

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
