---
# File: ansible-deploy.yml

- name: create ec2 instance
  hosts: 127.0.0.1
  connection: local
  roles:
    - create

- name: create deployment user on target
  hosts: app_host_group
  remote_user: ec2-user
  become: yes
  roles:
    - deployment_user
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/ec2-user/id_rsa"

- name: stage environment and deploy to target
  hosts: app_host_group
  remote_user: deployment
  roles:
    - stage
    - deploy
    - test
  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/deployment/id_rsa"
