---
# File:

- name: check if instance is in pending state and get details
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Project": "{{ instance_tag_project_name }}"
      "instance-state-name": pending
  register: matching_instances

- name: check if instance is in running state and get details
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Project": "{{ instance_tag_project_name }}"
      "instance-state-name": running
  register: matching_instances
  when: matching_instances.instances|length == 0

- name: set a variable to determine if instance is running
  set_fact:
    instance_present: "{{ matching_instances.instances|length > 0 }}"

- name: set variables for the specified vpc_id and subnet_id
  set_fact:
    vpc_id: "{{ (matching_instances.instances|first).vpc_id }}"
    subnet_id: "{{ (matching_instances.instances|first).id }}"
  when: instance_present
