---
# File:

# would use ec2_instance_facts if Ansbible 2.4 +
- name: check if instance is in pending state and get details
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Project": "{{ instance_tag_project_name }}"
      "instance-state-name": pending
  register: matching_instances

- set_fact:
    instance_count: "{{ matching_instances.instances|length }}"

- name: check if instance is in running state and get details
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Project": "{{ instance_tag_project_name }}"
      "instance-state-name": running
  register: matching_instances
  when: instance_count|int == 0

- set_fact:
    instance_count: "{{ matching_instances.instances|length }}"
  when: instance_count|int == 0
