---
# File:

- include: get_random_subnet.yml

- include: add_key.yml

- include: create_security_group.yml

- include: get_instance_details.yml

- include: create_instance.yml
  when: not instance_present

- include: get_instance_details.yml

- include: add_to_hosts_group.yml

- include: wait_for_ssh.yml
