---
# File:

- name: wait for ssh port to become available
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 10
    timeout: 120
    state: started
  with_items: "{{ matching_instances.instances }}"
