---

- name: install git
  package:
    name: git
  become: yes

- name: include rvm ruby version 2.3.1
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_rubies: ['ruby-2.3.1']
    rvm1_bundler_install: yes
    rvm1_user: deployment

- name: install nginx
  include: nginx.yml
  become: yes

- name: upgrade all packages on the instance
  yum:
    name: '*'
    state: latest
  become: yes
