---

- name: install git
  package:
    name: git

- name: include rvm ruby version 2.3.1
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_rubies: ['ruby-2.3.1']
    rvm1_install_flags: '--auto-dotfiles'
    rvm1_install_path: /usr/local/rvm
    rvm1_bundler_install: yes
    rvm1_user: root
  become: yes

- name: install nginx
  include: nginx.yml
