---
# File:

- name: install nginx
  package:
    name: nginx

- name: start nginx
  service:
    name: nginx
    enabled: yes
    state: started
  become: yes

- name: replace existing nginx.conf to allow the application web server to be on port 80
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    force: yes

- name: copy application template to /conf.d for proxying port {{ application_port }} with port 80
  template:
    src: application.conf.j2
    dest: /etc/nginx/conf.d/{{ server_application_name }}.conf
